### ISSUE TITLE
Directly modify entities using selectors

### ISSUE THREAD

**Issue by ngokevin** [ngokevin/aframe-mss#1]
Define using selectors:

``` css
.ball {
  geometry { primitive: sphere; }
  material { color: orange; roughness: 1 }
}
```

Entity somehow takes into account these properties:

``` html
<a-entity class="ball"></a-entity>
```
